### ISSUE TITLE
Refactor from mongosh to typescript

### ISSUE THREAD

**Issue by FlatBallFlyer** [agile-learning-institute/mentorHub-mongodb#98]
# SchemaManager
Refactor the existing mongosh scripts into typescript configuration-as-code product called SchemaManager. 
- [ ] A Typescript application connects to database, and processes the configuration files. This will replace both entry point.sh and migrate.js.
- [ ] Update to Configurations schema, i.e.:
```json
{
  "name": "someCollection",
  "versions": [
    {
      "version": "1.0.0",
      "indexes": [
        {
          "keys": {"personId": 1,"roadmapGroup": 1},
          "options": {"unique": false}
        }
      ]
    },
    {
      "version": "1.0.1",
      "prepare": "prepScript.js",
      "indexes": [
        {
          "keys": {"username": 1},
          "options": {"unique": true}
        }
      ],
      "postfix": "postScript.js"
    },
    {
      "version": "1.1.0"
    }
  ]
}
```
## For each version
- If provided the prepare script is executed.
- The specified version of schema is then applied.
- If provided the specified indexes are added.
- If provided the postscript is executed.
- The initial version will then optionally load test data 

# Implement schema pre-processors. 
The  ``sm``-preprocessor should have commands ``smType`` and ``smEnums`` and can be used as in:
## someSchema.yaml
```yaml
properties:
    lastSaved: 
        "description": "Breadcrumb of who last updated this document"
        "smType":"breadcrumb"
    userName:
        "description": "User name"
        "smType":"word"
    status:
        "description": "Status"
        "smEnums":"myStatus"
```
# Create preprocessor for smEnums
- [ ] Enums(listName) 
- [ ] Flat approach to enumerators (reusable)

# Create smTypes processor 
- [ ] process before smEnums, repeat until not found
- [ ] include type constraints from file in schemas folder

# Create default smTypes 
- [ ] Breadcrumb
- [ ] Word
- [ ] Sentence
- [ ] Paragraph
- [ ] eMail
- [ ] IP
- [ ] Phone
- [ ] StreetAddress
- [ ] URL
